### ISSUE TITLE
Unexpected error (os.listdir fails) on mnt_blob issue, refactor

### ISSUE THREAD

**Issue by rquintino** [Azure/ACE_Azure_ML#3]
existing check for existing mount not the best and fails first time, something like this?
(ignoring the Exception and not reporting also particularly nasty to debug)

if os.path.exists('/dbfs/mnt/data/'):
  print("Already mounted.")
else:
  dbutils.fs.mount(
    source = source,
    mount_point = mount_point,
    extra_configs = extra_configs)
  print("Mounted: %s at %s" % (source, mount_point))

**Comment by canoas** [comment]
#4 should fix this

**Comment by wmpauli** [comment]
thanks
