### ISSUE TITLE
01_introduction (cmd 46) - error: col("volt") not recognized

### ISSUE THREAD

**Issue by canoas** [Azure/ACE_Azure_ML#5]
this col() code depends on an import that was not available yet, it should be instead:
```
from pyspark.sql.functions import col
display(telemetryDF.filter(col("volt") > 250).limit(10))
```
alternatively, DF column can also be referenced without pyspark using:
```
display(telemetryDF.filter(telemetryDF.volt > 250).limit(10))
```
would prefer to submit a pull request, but these notebooks are somehow baked inside a binary file we imported at the beginning of the lab
[/presenter/notebooks.dbc](https://github.com/Azure/LearnAI_Azure_ML/blob/master/presenter/notebooks.dbc)

**Comment by wmpauli** [comment]
fixed. thank you
