### ISSUE TITLE
presenter/notebooks/day_1/01_introduction.ipynb auth failure with srorage

### ISSUE THREAD

**Issue by sqlshep** [Azure/ACE_Azure_ML#8]
the mnt notebook runs successfully, from teh intor notebook, however when you det to the "%fs ls /mnt/data/telemetry" command it fails with the following error. 

shaded.databricks.org.apache.hadoop.fs.azure.AzureException: com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

**Comment by sethmott** [comment]
Might be a jupyter magic issue. I would try this instead: `display(dbutils.fs.ls("dbfs:/foobar"))`
